/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Section = {
  _id: string;
  _type: "section";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  groupName: string;
  description?: string;
  showExtraFields?: boolean;
  blog?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "blog";
  }>;
  category?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tag: string;
};

export type Blog = {
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  category: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  tag: string;
  type?: "highlight";
  slug: Slug;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  shortDescription: string;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "normal"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  author: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  firstName: string;
  middleName: string;
  lastName: string;
  avatar: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Section
  | Category
  | Blog
  | Author
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./app/(pages)/(home)/page.tsx
// Variable: GET_BLOG_HIGHLIGHT
// Query: *[_type == "blog" && type == "highlight"]
export type GET_BLOG_HIGHLIGHTResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  category: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  tag: string;
  type?: "highlight";
  slug: Slug;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  shortDescription: string;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  author: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
}>;
// Variable: GET_CATEGORY_BANNER
// Query: *[    _type == "blog" &&      references(*[_type == "category" && tag == $categoryName][0]._id)    ]{      _id,      title,      featuredImage,      slug,      category,      shortDescription,      _createdAt    }
export type GET_CATEGORY_BANNERResult = Array<{
  _id: string;
  title: string;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  slug: Slug;
  category: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  shortDescription: string;
  _createdAt: string;
}>;
// Variable: GET_ALL_CATEGORY
// Query: *[_type == "category"]{      _id,      tag    }
export type GET_ALL_CATEGORYResult = Array<{
  _id: string;
  tag: string;
}>;
// Variable: GET_COVER_STORY
// Query: *[_type == "section" && groupName == "Cover Story"][0]{      groupName,      description,      category[]->{        _id,        tag      },      "blogs": *[        _type == "blog" &&        (          category._ref in ^.category[]._ref ||          count(category[@._ref in ^.category[]._ref]) > 0        )      ][0...6]{        _id,        _createdAt,        title,        slug,        featuredImage,        shortDescription,        category[]-> {          _id,          tag        }      }    }
export type GET_COVER_STORYResult = {
  groupName: string;
  description: string | null;
  category: Array<{
    _id: string;
    tag: string;
  }> | null;
  blogs: Array<{
    _id: string;
    _createdAt: string;
    title: string;
    slug: Slug;
    featuredImage: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    shortDescription: string;
    category: Array<{
      _id: string;
      tag: string;
    }>;
  }>;
} | null;

// Source: ./sanity/lib/queries.ts
// Variable: GET_CATEGORIES
// Query: *[_type == "category"]
export type GET_CATEGORIESResult = Array<{
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  tag: string;
}>;
// Variable: GET_BLOG
// Query: *[_type == "blog"]
export type GET_BLOGResult = Array<{
  _id: string;
  _type: "blog";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  category: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "category";
  }>;
  tag: string;
  type?: "highlight";
  slug: Slug;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  shortDescription: string;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  author: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
}>;
// Variable: GET_BLOG_BY_CATEGORY
// Query: *[  _type == "blog" &&  $tag in category[]->tag]{  title,  slug,  type,  shortDescription,  featuredImage,  _createdAt,  category[]->{    tag  }}
export type GET_BLOG_BY_CATEGORYResult = Array<{
  title: string;
  slug: Slug;
  type: "highlight" | null;
  shortDescription: string;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  _createdAt: string;
  category: Array<{
    tag: string;
  }>;
}>;
// Variable: GET_BLOG_BY_SLUG
// Query: *[_type == "blog" && slug.current == $slug][0]{  title,  slug,  shortDescription,  body,  featuredImage,  _createdAt,  author-> {     firstName,     middleName,     lastName,     avatar   },  category[]-> { title }}
export type GET_BLOG_BY_SLUGResult = {
  title: string;
  slug: Slug;
  shortDescription: string;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          | "blockquote"
          | "h1"
          | "h2"
          | "h3"
          | "h4"
          | "h5"
          | "h6"
          | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
        _key: string;
      }
  >;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  _createdAt: string;
  author: {
    firstName: string;
    middleName: string;
    lastName: string;
    avatar: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
  };
  category: Array<{
    title: null;
  }>;
} | null;
// Variable: GET_LATEST_BLOG
// Query: *[_type == "blog"] | order(_createdAt desc)[0...3]{    title,    slug,    shortDescription,    featuredImage,    _createdAt,    category[]->{      title    }  }
export type GET_LATEST_BLOGResult = Array<{
  title: string;
  slug: Slug;
  shortDescription: string;
  featuredImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  _createdAt: string;
  category: Array<{
    title: null;
  }>;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "blog" && type == "highlight"]': GET_BLOG_HIGHLIGHTResult;
    '*[\n    _type == "blog" &&\n      references(*[_type == "category" && tag == $categoryName][0]._id)\n    ]{\n      _id,\n      title,\n      featuredImage,\n      slug,\n      category,\n      shortDescription,\n      _createdAt\n    }\n  ': GET_CATEGORY_BANNERResult;
    '*[_type == "category"]{\n      _id,\n      tag\n    }\n  ': GET_ALL_CATEGORYResult;
    '*[_type == "section" && groupName == "Cover Story"][0]{\n      groupName,\n      description,\n\n      category[]->{\n        _id,\n        tag\n      },\n\n      "blogs": *[\n        _type == "blog" &&\n        (\n          category._ref in ^.category[]._ref ||\n          count(category[@._ref in ^.category[]._ref]) > 0\n        )\n      ][0...6]{\n        _id,\n        _createdAt,\n        title,\n        slug,\n        featuredImage,\n        shortDescription,\n        category[]-> {\n          _id,\n          tag\n        }\n      }\n    }\n  ': GET_COVER_STORYResult;
    '*[_type == "category"]': GET_CATEGORIESResult;
    '*[_type == "blog"]': GET_BLOGResult;
    '*[\n  _type == "blog" &&\n  $tag in category[]->tag\n]{\n  title,\n  slug,\n  type,\n  shortDescription,\n  featuredImage,\n  _createdAt,\n  category[]->{\n    tag\n  }\n}\n': GET_BLOG_BY_CATEGORYResult;
    '*[_type == "blog" && slug.current == $slug][0]{\n  title,\n  slug,\n  shortDescription,\n  body,\n  featuredImage,\n  _createdAt,\n  author-> { \n    firstName, \n    middleName, \n    lastName, \n    avatar \n  },\n  category[]-> { title }\n}': GET_BLOG_BY_SLUGResult;
    '*[_type == "blog"] | order(_createdAt desc)[0...3]{\n    title,\n    slug,\n    shortDescription,\n    featuredImage,\n    _createdAt,\n    category[]->{\n      title\n    }\n  }': GET_LATEST_BLOGResult;
  }
}
